version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  search-module-1:
    image: sumitdockerspace/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=searchmodule.xml
    volumes:
      - ./searchmodule-1-result:/usr/sumit/docker-selenium/test-output
  search-module-2:
    image: sumitdockerspace/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=searchmodule.xml
    volumes:
      - ./searchmodule-2-result:/usr/sumit/docker-selenium/test-output
  bookflight-1-module:
    image: sumitdockerspace/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=bookflightmodule.xml
    volumes:
      - ./bookflight-1-result:/usr/sumit/docker-selenium/test-output
  bookflight-module-2:
    image: sumitdockerspace/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=bookflightmodule.xml
    volumes:
      - ./bookflight-2-result:/usr/sumit/docker-selenium/test-output